name: CI with SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0                          # Recommended for full history :contentReference[oaicite:2]{index=2}

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn -B clean verify                 # Ensures target/classes is populated :contentReference[oaicite:3]{index=3}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        with:
          projectBaseDir: .                     # Loads sonar-project.properties from repo root :contentReference[oaicite:4]{index=4}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub :contentReference[oaicite:5]{index=5}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}   # Set in Settings → Secrets :contentReference[oaicite:6]{index=6}
